using System.Collections.Generic;
using System.Linq;
using System.Text;
using Features.CodeGeneratorModule.CustomCodeGeneratorModule.Scripts.Editor.Core;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace Features.AddressablesConstantGeneratorModule.Editor {
    // Writes Address_g.cs: one nested class per non-empty Addressables group, one const per entry address.
    [Generator]
    public sealed class AddressablesConstantGenerator : ICodeGenerator {
        private const string GENERATED_FILES_PATH = "Assets/Features/AddressablesConstantGeneratorModule/Generated";
        private const string FILE_NAME = "Address_g.cs";
        private const string NAMESPACE = "Features.AddressablesConstantsGenerator.Generated";

        public void Execute(GeneratorContext context) {
            AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null) {
                Debug.LogError("[AddressablesConstantGenerator] Addressable settings not found, Address_g.cs not generated.");
                return;
            }

            context.OverrideFolderPath(GENERATED_FILES_PATH);
            context.AddCode(FILE_NAME, BuildSource(settings));
        }

        private static string BuildSource(AddressableAssetSettings settings) {
            List<(string className, string groupName, List<string> addresses)> groups = settings.groups
                .Where(group => group != null && !group.ReadOnly)
                .Select(group => (ToIdentifier(group.Name), group.Name, group.entries.Select(entry => entry.address).ToList()))
                .Where(group => group.Item3.Count > 0)
                .ToList();

            StringBuilder builder = new();
            builder.Append("// <auto-generated/>\n");
            builder.Append("#nullable enable\n\n");
            builder.Append("using System.Collections.Generic;\n");
            builder.Append($"namespace {NAMESPACE} {{\n");
            builder.Append("    public partial class Address {\n");

            foreach ((string className, string groupName, List<string> addresses) in groups) {
                builder.Append($"        public static partial class {className} {{\n");
                builder.Append($"            public const string ADDRESSABLE_GROUP_NAME = \"{groupName}\";\n");
                foreach (string address in addresses)
                    builder.Append($"            public const string {ToIdentifier(address)} = \"{address}\";\n");
                builder.Append("            public static List<string> AllAddressablesInGroup = new List<string>() {");
                foreach (string address in addresses)
                    builder.Append($"\"{address}\",");
                builder.Append("};\n");
                builder.Append("        }\n");
            }

            builder.Append("        public static partial class Groups {\n");
            builder.Append("            public static List<List<string>> AllAddressablesGroups = new List<List<string>>() {");
            foreach ((string className, _, _) in groups)
                builder.Append($"{className}.AllAddressablesInGroup,");
            builder.Append("};\n");
            builder.Append("            public static List<string> AllAddressablesGroupNames = new List<string>() {");
            foreach ((string className, _, _) in groups)
                builder.Append($"{className}.ADDRESSABLE_GROUP_NAME,");
            builder.Append("};\n");
            builder.Append("        }\n");
            builder.Append("    }\n");
            builder.Append("}\n");
            return builder.ToString();
        }

        private static string ToIdentifier(string value) {
            StringBuilder builder = new();
            foreach (char symbol in value)
                if (char.IsLetterOrDigit(symbol) || symbol == '_')
                    builder.Append(symbol);

            if (builder.Length == 0 || char.IsDigit(builder[0]))
                builder.Insert(0, '_');
            return builder.ToString();
        }
    }
}
